/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchCity: typeof import('./components/SearchCity.vue')['default']
    Weather: typeof import('./components/Weather.vue')['default']
  }
}
